### PR TITLE
added translations options

### PR DESCRIPTION
**Pull request by wolxXx**
see https://github.com/nadangergeo/RWD-Table-Patterns/issues/27
as I needed it too, I just created the fix :)

### CODE REVIEW

**Comment by nadangergeo** [comment]
Nice job, thank you! 👍

**Comment by wolxXx** [comment]
thank you! :)

**Comment by nadangergeo** [comment]
Have you checked out the dev-branch? It has a bunch of bug-fixes, but it needs to be tested. Any help testing the branch is appreciated! ✌️

**Comment by wolxXx** [comment]
not yet. will do it soon :)

**Comment by wolxXx** [comment]
would you please create a new release, where this is included?
thanks :)

**Comment by nadangergeo** [comment]
Already did it a while ago, see the latest commits. It's included in v.5.1.0 :-)

**Comment by nadangergeo** [comment]
I still need help testing the dev-branch by the way 😁

**Comment by wolxXx** [comment]
my fault. :)
times are busy.. sorry. soon! promised!

**Pull request merged**
